DELETE FROM explore_tasks;

INSERT INTO explore_tasks (title, action_url, coins_reward, xp_reward, order_index, is_active) VALUES
('Complete your <strong>Profile</strong> setup', '/profile', 19, 28, 1, true),
('Set a <strong>Daily Study Goal</strong>', '/settings', 14, 25, 2, true),
('Explore the <strong>Backpack</strong>', '/backpack', 13, 28, 3, true),
('Create your first <strong>Folder</strong>', '/backpack', 11, 18, 4, true),
('Upload a <strong>PDF Document</strong>', '/upload', 11, 18, 5, true),
('Read a document in the <strong>Workstation</strong>', '/workstation', 6, 12, 6, true),
('Create your first <strong>Flashcard Deck</strong>', '/decks?new=1', 13, 16, 7, true),
('Study 10 <strong>Flashcards</strong>', '/decks', 5, 13, 8, true),
('Take a <strong>Mock Exam</strong>', '/mock-exam', 12, 18, 9, true),
('Write a <strong>Study Note</strong>', '/notes?new=1', 12, 18, 10, true),
('Use <strong>AI Chat</strong> to understand a topic', '/ai-chat', 16, 29, 11, true),
('Check your <strong>Analytics</strong>', '/analytics', 11, 12, 12, true),
('Visit the <strong>Coin Store</strong>', '/store', 16, 16, 13, true),
('Equip a new <strong>Avatar</strong>', '/profile', 11, 26, 14, true),
('Join a <strong>Study Group</strong>', '/study-groups', 14, 21, 15, true),
('Send a message in a <strong>Group Chat</strong>', '/study-groups', 7, 11, 16, true),
('Play a match of <strong>Knowledge Heist</strong>', '/heist', 16, 11, 17, true),
('Compete in the <strong>Playground</strong>', '/compete', 14, 20, 18, true),
('Refer a <strong>Friend</strong> to Luter', '/refer', 15, 26, 19, true),
('Read the <strong>Wall of Love</strong>', '/wall-of-love', 19, 22, 20, true),
('Reach a <strong>3-Day Streak</strong>', '/streak', 6, 15, 21, true),
('Reach a <strong>7-Day Streak</strong>', '/streak', 14, 35, 22, true),
('Reach a <strong>14-Day Streak</strong>', '/streak', 28, 70, 23, true),
('Reach a <strong>21-Day Streak</strong>', '/streak', 42, 105, 24, true),
('Reach a <strong>30-Day Streak</strong>', '/streak', 60, 150, 25, true),
('Reach a <strong>50-Day Streak</strong>', '/streak', 100, 250, 26, true),
('Reach a <strong>100-Day Streak</strong>', '/streak', 200, 500, 27, true),
('Reach a <strong>150-Day Streak</strong>', '/streak', 300, 750, 28, true),
('Reach a <strong>200-Day Streak</strong>', '/streak', 400, 1000, 29, true),
('Reach a <strong>365-Day Streak</strong>', '/streak', 730, 1825, 30, true),
('Reach <strong>Level 2</strong>', '/profile', 10, 20, 31, true),
('Reach <strong>Level 3</strong>', '/profile', 15, 30, 32, true),
('Reach <strong>Level 4</strong>', '/profile', 20, 40, 33, true),
('Reach <strong>Level 5</strong>', '/profile', 25, 50, 34, true),
('Reach <strong>Level 6</strong>', '/profile', 30, 60, 35, true),
('Reach <strong>Level 7</strong>', '/profile', 35, 70, 36, true),
('Reach <strong>Level 8</strong>', '/profile', 40, 80, 37, true),
('Reach <strong>Level 9</strong>', '/profile', 45, 90, 38, true),
('Reach <strong>Level 10</strong>', '/profile', 50, 100, 39, true),
('Reach <strong>Level 11</strong>', '/profile', 55, 110, 40, true),
('Reach <strong>Level 12</strong>', '/profile', 60, 120, 41, true),
('Reach <strong>Level 13</strong>', '/profile', 65, 130, 42, true),
('Reach <strong>Level 14</strong>', '/profile', 70, 140, 43, true),
('Reach <strong>Level 15</strong>', '/profile', 75, 150, 44, true),
('Reach <strong>Level 16</strong>', '/profile', 80, 160, 45, true),
('Reach <strong>Level 17</strong>', '/profile', 85, 170, 46, true),
('Reach <strong>Level 18</strong>', '/profile', 90, 180, 47, true),
('Reach <strong>Level 19</strong>', '/profile', 95, 190, 48, true),
('Reach <strong>Level 20</strong>', '/profile', 100, 200, 49, true),
('Study <strong>50 Flashcards</strong>', '/decks', 10, 25, 50, true),
('Study <strong>100 Flashcards</strong>', '/decks', 20, 50, 51, true),
('Study <strong>250 Flashcards</strong>', '/decks', 50, 125, 52, true),
('Study <strong>500 Flashcards</strong>', '/decks', 100, 250, 53, true),
('Study <strong>1000 Flashcards</strong>', '/decks', 200, 500, 54, true),
('Complete <strong>5 Mock Exams</strong>', '/mock-exam', 25, 50, 55, true),
('Complete <strong>10 Mock Exams</strong>', '/mock-exam', 50, 100, 56, true),
('Complete <strong>25 Mock Exams</strong>', '/mock-exam', 125, 250, 57, true),
('Complete <strong>50 Mock Exams</strong>', '/mock-exam', 250, 500, 58, true),
('Complete <strong>Daily Study Challenge #1</strong>', '/home', 10, 20, 59, true),
('Complete <strong>Daily Study Challenge #2</strong>', '/home', 10, 20, 60, true),
('Complete <strong>Daily Study Challenge #3</strong>', '/home', 10, 20, 61, true),
('Complete <strong>Daily Study Challenge #4</strong>', '/home', 10, 20, 62, true),
('Complete <strong>Daily Study Challenge #5</strong>', '/home', 10, 20, 63, true),
('Complete <strong>Daily Study Challenge #6</strong>', '/home', 10, 20, 64, true),
('Complete <strong>Daily Study Challenge #7</strong>', '/home', 10, 20, 65, true),
('Complete <strong>Daily Study Challenge #8</strong>', '/home', 10, 20, 66, true),
('Complete <strong>Daily Study Challenge #9</strong>', '/home', 10, 20, 67, true),
('Complete <strong>Daily Study Challenge #10</strong>', '/home', 10, 20, 68, true),
('Complete <strong>Daily Study Challenge #11</strong>', '/home', 10, 20, 69, true),
('Complete <strong>Daily Study Challenge #12</strong>', '/home', 10, 20, 70, true),
('Complete <strong>Daily Study Challenge #13</strong>', '/home', 10, 20, 71, true),
('Complete <strong>Daily Study Challenge #14</strong>', '/home', 10, 20, 72, true),
('Complete <strong>Daily Study Challenge #15</strong>', '/home', 10, 20, 73, true),
('Complete <strong>Daily Study Challenge #16</strong>', '/home', 10, 20, 74, true),
('Complete <strong>Daily Study Challenge #17</strong>', '/home', 10, 20, 75, true),
('Complete <strong>Daily Study Challenge #18</strong>', '/home', 10, 20, 76, true),
('Complete <strong>Daily Study Challenge #19</strong>', '/home', 10, 20, 77, true),
('Complete <strong>Daily Study Challenge #20</strong>', '/home', 10, 20, 78, true),
('Complete <strong>Daily Study Challenge #21</strong>', '/home', 10, 20, 79, true),
('Complete <strong>Daily Study Challenge #22</strong>', '/home', 10, 20, 80, true),
('Complete <strong>Daily Study Challenge #23</strong>', '/home', 10, 20, 81, true),
('Complete <strong>Daily Study Challenge #24</strong>', '/home', 10, 20, 82, true),
('Complete <strong>Daily Study Challenge #25</strong>', '/home', 10, 20, 83, true),
('Complete <strong>Daily Study Challenge #26</strong>', '/home', 10, 20, 84, true),
('Complete <strong>Daily Study Challenge #27</strong>', '/home', 10, 20, 85, true),
('Complete <strong>Daily Study Challenge #28</strong>', '/home', 10, 20, 86, true),
('Complete <strong>Daily Study Challenge #29</strong>', '/home', 10, 20, 87, true),
('Complete <strong>Daily Study Challenge #30</strong>', '/home', 10, 20, 88, true),
('Complete <strong>Daily Study Challenge #31</strong>', '/home', 10, 20, 89, true),
('Complete <strong>Daily Study Challenge #32</strong>', '/home', 10, 20, 90, true),
('Complete <strong>Daily Study Challenge #33</strong>', '/home', 10, 20, 91, true),
('Complete <strong>Daily Study Challenge #34</strong>', '/home', 10, 20, 92, true),
('Complete <strong>Daily Study Challenge #35</strong>', '/home', 10, 20, 93, true),
('Complete <strong>Daily Study Challenge #36</strong>', '/home', 10, 20, 94, true),
('Complete <strong>Daily Study Challenge #37</strong>', '/home', 10, 20, 95, true),
('Complete <strong>Daily Study Challenge #38</strong>', '/home', 10, 20, 96, true),
('Complete <strong>Daily Study Challenge #39</strong>', '/home', 10, 20, 97, true),
('Complete <strong>Daily Study Challenge #40</strong>', '/home', 10, 20, 98, true),
('Complete <strong>Daily Study Challenge #41</strong>', '/home', 10, 20, 99, true),
('Complete <strong>Daily Study Challenge #42</strong>', '/home', 10, 20, 100, true);
